name: Latest blog posts
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://staskus.io/feed/"
          max_post_count: 5
          template: "$newline- $date [$title]($url)"
          locale: "en"
          date_format: "medium"
